feat(files): publish task for Files API as content storage
evrythng/dashboard-customers-starter pull request #2
Opened 2017-01-09 14:42 UTC by iamfrontender

https://evrythng.atlassian.net/browse/FE-45

2017-01-09 14:44 UTC, C-D-Lewis commented on README.md
> +EVRYTHNG platform provides powerful cloud file system, or Files API, which could be used
"The EVRYTHNG Platform provides a powerful cloud file storage system..."

2017-01-09 14:44 UTC, C-D-Lewis commented on README.md
> +to store your custom components. Files API requires an API key with valid permissions to be provided from environment. It could be done either with `EVT_AUTH` environment variable or `~./evt-auth` fi
"The Files API requires..."

2017-01-09 16:24 UTC, joaovieira requested changes

2017-01-09 16:24 UTC, joaovieira commented on README.md
> +  * builds and deploys the components to EVRYTHNG platform using Files API. [Read below](#deploying-using-files-api) for usage details.
the Files API. provide link to Files API documentation in readme.io

2017-01-09 16:24 UTC, joaovieira commented on README.md
> +### Deploying using Files API
the Files API

2017-01-09 16:24 UTC, joaovieira commented on gulpfile.babel.js
> +  webpackConfig.entry[config.name] = config.paths.entry;
If you want to make the name configurable, it should be the same for the 'webpack' and the 'serve' tasks (serve is still using 'components'). Also, they can be defined directly in the webpack.config.js.

2017-01-09 16:24 UTC, joaovieira commented on gulpfile.babel.js
> +  webpackConfig.entry[config.name] = config.paths.entry;
`webpack` is the build task, should use the dist config. `webpack` and `serve` are swapped.

2017-01-09 16:24 UTC, joaovieira commented on gulpfile.babel.js
> +  compiler = webpack(webpackDistConfig);
`const compiler`

2017-01-09 16:24 UTC, joaovieira commented on gulpfile.babel.js
> +gulp.task('publish', ['build'], () => deployWidgets());
upgrade to Gulp 4

2017-01-09 16:24 UTC, joaovieira commented on tasks/config.js
> +function inRoot(glob = '') {
`resolveToRoot` is better/more expressive (why changing existing code?)

2017-01-09 16:24 UTC, joaovieira commented on tasks/copy-template.js
> +'use strict';
no need to use strict in ES modules, btw

2017-01-09 16:24 UTC, joaovieira commented on tasks/copy-template.js
> +  const destPath = path.join(root, type + 's', parentPath, name);
what's root in here? did you try this?

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +////////////////////////////////////////////
remove

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +import getApiKey from './get-api-key';
modules should not contain verbs (moreover that module exports several things...). call it `evtUtils` or something like that, with a readApiKey exported method.

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +  readEnvironment,
why get for some, read for others? keep it consistent.

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +import projectConfig from './config';
config = config

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +const config = {
yet another config. you can have multiple constant variables..

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +    webpackConfig.output.path,
dist config

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +    .then(() => console.log('//////////', evrythng.settings.apiKey))
is this meant to stay? a log with '////' doesn't say anything

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +export default () => {
comment/docs

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +function getMeta() {
comment/docs, same below

2017-01-09 16:24 UTC, joaovieira commented on tasks/deploy-widgets.js
> +  return new Promise((res, rej) => {
resolve, reject (res may be misunderstood by response, which is the most common)

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +let config = {
another config, use first level constants instead

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +/////////////////////////////////////////////////////////////////
remove

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +export {
use export keywords on the methods instead of exporting an object

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +/////////////////////////////////////////////////////////////////
remove

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +function getAPIKey() {
comment/docs

2017-01-09 16:24 UTC, joaovieira commented on README.md
> +to store your custom components. Files API requires an API key with valid permissions to be provided from environment. It could be done either with `EVT_AUTH` environment variable or `~./evt-auth` fi
do not force people to dirty their home environment.

1) use env variable; or allow people to pass the key in the arguments
2) what would be the structure of the file? if there's only one variable, there's no need for a file. also, we may have a proper credentials/profiles/configuration file in the future, so we better not define such a structure now

(path was also wrong: `~/.evt-auth`)

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +    let authFile = path.join(expandTilde('~'), config.file);
see comment in readme, remove this tilde dependency

2017-01-09 16:24 UTC, joaovieira commented on tasks/get-api-key.js
> +function setup(newConfig) {
where is this used?

2017-01-09 16:24 UTC, joaovieira commented on webpack.config.js
> +var path = require('path');
const or import

2017-01-09 16:24 UTC, joaovieira commented on webpack.config.js
>  module.exports = {
es6 modules

2017-01-11 10:29 UTC, joaovieira requested changes

2017-01-11 10:29 UTC, joaovieira commented on gulpfile.babel.js
> +gulp.task('build', gulp.series('webpack'));
https://github.com/gulpjs/gulp/issues/844#issuecomment-68311119

2017-01-11 10:29 UTC, joaovieira commented on tasks/copy-template.js
> -'use strict';
remove everywhere

2017-01-11 10:29 UTC, joaovieira commented on tasks/deploy-widgets.js
> +  return readAPIKeyFromEnvironment()
environment means environment variable? no need to add implementation details to the method name (we can change the way you read it at some point in the future). simply `readApiKey` is fine

2017-01-11 10:29 UTC, joaovieira commented on tasks/evt-utils.js
> +  return Promise.resolve(process.env['EVT_AUTH']);
if it's just for this, it can stay in the deploy file

2017-01-11 10:29 UTC, joaovieira commented on tasks/deploy-widgets.js
>      let req = request.put({
`const req`, `const fileStream`.

use `resolve` and `reject` as well.

2017-01-23 11:11 UTC, joaovieira requested changes

2017-01-23 11:11 UTC, joaovieira commented on gulpfile.babel.js
> +  return gulp.series(compile, deployWidgets)();
don't use gulp series/parallel methods in tasks definitions. use only in task registration below (that's where you orchestrate the task flow using the various subtasks):

```javascript
gulp.task('publish', gulp.series(build, publish));
```

2017-01-23 12:54 UTC, joaovieira approved these changes

2017-01-23 13:18 UTC, merged